spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: ivan
server:
  port: 8000
logging:
  level:
    root: INFO

  redis:
    host: localhost
    port: 6379
    timeout: 10000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1
